name: Deploy prod schema migrations

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/prod/**"
  workflow_dispatch: {}

concurrency:
  group: prod-migrations
  cancel-in-progress: false

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}          # e.g., khyeerjgjzyffnurkval
      DB_HOST: aws-1-us-east-2.pooler.supabase.com              # transaction pooler
      DB_PORT: "6543"
      DB_NAME: postgres                                         # Supabase default DB
      DB_ROLE: github_action                                    # your role in Postgres
      DB_PASS: ${{ secrets.SUPABASE_GITHUB_ROLE_PASSWORD }}     # create/store this secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # Build pooled username: <role>.<project_ref>
      - name: Build pooled username and URL
        run: |
          echo "DB_USER_POOLED=${DB_ROLE}.${PROJECT_REF}" >> "$GITHUB_ENV"
          echo "DB_URL=postgresql://${DB_ROLE}.${PROJECT_REF}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require" >> "$GITHUB_ENV"

      # Guardrail: prod migrations must target the prod schema only
      - name: Validate migration files only target prod schema
        run: |
          set -e
          if grep -RInE '\b(auth|storage|graphql_public|extensions|public)\.' supabase/migrations/prod || \
             grep -RInE '\bALTER SCHEMA\b(?!\s+prod\b)' supabase/migrations/prod || \
             grep -RInE '\bCREATE SCHEMA\b(?!\s+IF NOT EXISTS\s+prod\b)' supabase/migrations/prod ; then
            echo "::error ::Detected references to non-prod schemas in prod migrations."
            exit 1
          fi

      - name: Apply prod migrations (single transaction per file)
        run: |
          set -euo pipefail
          shopt -s nullglob
          FILES=(supabase/migrations/prod/V*__*.sql)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No migration files to apply."
            exit 0
          fi
          for f in "${FILES[@]}"; do
            echo "Applying $f"
            # -v ON_ERROR_STOP=1: fail on first error in the file
            # -1 : wrap the entire file in a single transaction
            psql "${DB_URL}" -v ON_ERROR_STOP=1 -1 -f "$f"
          done