name: Deploy prod schema migrations

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**"
  workflow_dispatch: {}

concurrency:
  group: prod-migrations
  cancel-in-progress: false

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      DB_HOST: aws-1-us-east-2.pooler.supabase.com
      DB_PORT: "6543"
      DB_ROLE: github_action
      DB_PASS: ${{ secrets.SUPABASE_GITHUB_ROLE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Build pooled username and URL
        run: |
          echo "DB_USER_POOLED=${DB_ROLE}.${PROJECT_REF}" >> "$GITHUB_ENV"
          echo "DB_URL=postgresql://${DB_ROLE}.${PROJECT_REF}:${DB_PASS}@aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require" >> "$GITHUB_ENV"

      - name: Apply prod migrations
        run: |
          set -euo pipefail
          shopt -s nullglob
          FILES=(supabase/migrations/V*__*.sql)
          echo "$FILES"